# Copyright 2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

ingress:
  controllerType: ingress-nginx

wellKnownDelegation:
  ingress:
    tlsSecret: "{{ $.Release.Name }}-well-known-web-tls"

haproxy:
  podSecurityContext:
    runAsGroup: 0
